/*// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'; 
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  datasource: {
    url: process.env.DATABASE_URL, 
  },
  migrations: {
    seed: 'npx tsx ./prisma/seed.ts',
  },
});*/

// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

/*import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: 'npx tsx prisma/seed.ts',
  },
  datasource: {
    url: process.env["DATABASE_URL"] || "",
  },
});
*/

import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import { defineConfig } from '@prisma/config';

const connectionString = process.env.DATABASE_URL;

const isLocalhost =
  connectionString?.includes('localhost') ||
  connectionString?.includes('127.0.0.1');

const pool = new Pool({
  connectionString,
  ssl: isLocalhost ? false : { rejectUnauthorized: false },
});

const adapter = new PrismaPg(pool);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: 'npx tsx prisma/seed.ts',
  },
  datasource: {
    url: process.env["DATABASE_URL"] || "",
  },
  adapter,
});