export const defaultGroups = [
  {
    id: 'ducks-default',
    name: 'Ducks',
    image: '/groups/ducks.jpg',
    members: 3,
    maxmembers: 5,
    intensity: 'high',
    description: 'Looking to add a couple more members to our small group. We tend to go on more difficult hikes, so please only consider if you have more experience.',
    owner: 'john@foo.com',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Koko Head',
  },
  {
    id: 'math-hikes-default',
    name: 'Mathemagical Hikes',
    image: '/groups/mathclub.jpeg',
    members: 10,
    maxmembers: null,
    intensity: 'easy',
    description: 'We go on hikes and talk about math. Please join if interested, we always welcome new members. Hikes typically range from relatively easy to moderate.',
    owner: 'john@foo.com',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Manoa Falls',
  },
  {
    id: 'hnl-hiking-default',
    name: 'HNL Hiking Club',
    image: '/groups/hnlhike.jpeg',
    members: 55,
    maxmembers: null,
    intensity: 'moderate',
    description: 'We heard about this website and wanted to branch out. Our group number is bigger than what is listed but we have only included members that have profiles here. Always welcome more and every hike is a big crowd.',
    owner: 'john@foo.com',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Diamond Head',
  },
  {
    id: 'brunch-girls-default',
    name: 'Brunch Club with the Girls',
    image: '/groups/brunch.jpg',
    members: 25,
    maxmembers: null,
    intensity: 'easy',
    description: 'We love brunch. Seriously we know all the best spots. Please come and join everyone is welcome',
    owner: 'jane@foo.com',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Makapuu Lighthouse',
  },
  {
    id: 'camp-default',
    name: 'Camping and Hiking',
    image: '/groups/camp.jpg',
    members: 7,
    maxmembers: null,
    intensity: 'hard',
    description: 'We love finding the best spots to go camping. We also do hikes occasionally, especially during the very busy weeks before finals ;-;',
    owner: 'jane@foo.com',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Wiliwilinui Ridge Trail',
  },
  {
    id: 'ams-default',
    name: 'Anime and Manga Society of Hawaii',
    image: '/groups/ams.jpg',
    members: 73,
    maxmembers: null,
    intensity: 'easy',
    description: 'Talking about anime and manga while looking at beautiful nature. We occasionally have watch parties and things too.',
    owner: 'jane@foo.com',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Manoa Falls',
  },
  {
    id: 'boba-default',
    name: 'Boba Time',
    image: '/groups/boba.jpg',
    members: 9,
    maxmembers: 15,
    intensity: 'easy',
    description: 'We focus on talking about feelings with each other. Sometimes having a hard week and sharing it with others makes it less hard. Exercise can also help make you feel better. We are not sure if we fully believe that but we do believe if you do it with others, then you will feel better for sure. (Looking for new members currently as some people have graudated recently.)',
    owner: 'john@foo.com',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Manoa Falls',
  },
  {
    id: 'baking-default',
    name: 'Muffin Time',
    image: '/groups/baking.jpg',
    members: 34,
    maxmembers: 40,
    intensity: 'moderate',
    description: 'We love baking! Bring your best recipes for protein/granola bars. Please only consider joining if you enjoy moderately difficult hikes though.',
    owner: 'john@foo.com',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Waimano Falls Trail',
  },
  {
    id: 'poke-default',
    name: 'Local Grindz',
    image: '/groups/poke.jpg',
    members: 3,
    maxmembers: null,
    intensity: 'easy',
    description: 'Just joined recently. Excited to meet new people and eat new delicious foods. Please join and let us know any reccomendations you have.',
    owner: 'john@foo.com',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Manoa Falls',
  },
  {
    id: 'bird-watchers-default',
    name: 'Bird Watchers',
    image: '/groups/birdwatchers.jpg',
    members: 78,
    maxmembers: 100,
    intensity: 'moderate',
    description: 'Love Bird Watching? Consider joining our group. We love talking about the many different types of birds, migration patterns, anything you can think of. We also try to give tea to drink!',
    owner: 'jane@foo.com',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Olomana Three Peaks Trail',
  },
  {
    id: 'game-default',
    name: 'Gamers Yo',
    image: '/groups/game.jpg',
    members: 23,
    maxmembers: null,
    intensity: 'easy',
    description: 'After hiking, we play video games. Mostly Super Smash Bros and Mario Kart, although we are open to more suggestions.',
    owner: 'jane@foo.com',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Manoa Falls',
  },
  {
    id: 'isa-default',
    name: 'International Student Association',
    image: '/groups/isa.jpg',
    members: 57,
    maxmembers: null,
    intensity: 'moderate',
    description: 'Meet other International Exchange Students through Hiking. We also have picnics after the hike is over. Everyone is welcome',
    owner: 'jane@foo.com',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Makapuu Lighthouse',
  },
  {
    id: 'running-default',
    name: 'Running Club - Manoa Chapter',
    image: '/groups/running.jpg',
    members: 63,
    maxmembers: null,
    intensity: 'hard',
    description: 'We love going on runs and wanted to expand trying hikes as well. Please only consider joining if you have quite a bit of experience with hiking.',
    owner: 'jane@foo.com',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Kaʻena Point Trail',
  },
  {
    id: 'acm-default',
    name: 'Association for Computing Machinery',
    image: '/groups/acm.png',
    members: 65,
    maxmembers: null,
    intensity: 'easy',
    description: 'We heard about this project and wanted to put a group in. We love talking about anything related. If you have any questions regarding the computer science department and what we do here, please let us know.',
    owner: 'john@foo.com',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Manoa Falls',
  },
  {
    id: 'instrument-default',
    name: 'Jazz - The Rocks Band',
    image: '/groups/instrument.jpg',
    members: 7,
    maxmembers: 10,
    intensity: 'moderate',
    description: 'We like playing together in band. Please message us and we will let you know if you would be a good fit.',
    owner: 'john@foo.com',
    lastdate: new Date('2026-07-24T09:00:00'),
    lastlocation: 'Aiea Loop Trail',
  },
];

export default defaultGroups;