export const defaultEvents = [
	{
		id: 'summer-hiking-meetup',
		title: 'Summer Hiking Meetup',
		description: 'Join fellow hikers for a community hike at Manoa Falls. We will meet in the morning, hike together through the trail, and enjoy the scenery while connecting with other members of the hiking community. This event is open to hikers of all experience levels.',
		date: new Date('2026-07-30T09:00:00'),
		location: 'Manoa Falls',
		image: '/manoa-falls.jpg',
	},
	{
		id: 'trail-cleanup-day',
		title: 'Trail Cleanup Day',
		description: 'Help keep Hawaii trails beautiful with our cleanup event. Volunteers will work together to remove litter, maintain pathways, and help preserve the natural areas we enjoy. Bring water, comfortable shoes, and a willingness to help the community.',
		date: new Date('2026-08-15T09:00:00'),
		location: 'TBD',
		image: '/trail-cleanup.jpg',
	},
	{
		id: 'new-hiking-recommendations',
		title: 'New Hiking Recommendations',
		description: 'We added new trails and recommendations to explore. Check out our updated hiking collection featuring new locations, difficulty information, and recommendations for hikers looking for their next adventure.',
		date: new Date('2026-07-24T09:00:00'),
		location: 'Online',
		image: '/oblogo-better.png',
	},
	{
		id: 'diamond-head-sunrise-hike',
		title: 'Diamond Head Sunrise Hike',
		description: 'Start your morning with a group hike to the summit of Diamond Head. We will meet before sunrise and make our way up the trail together to enjoy the views of Waikiki and the surrounding coastline. Hikers should bring water and comfortable shoes.',
		date: new Date('2026-08-22T05:30:00'),
		location: 'Diamond Head',
		image: '/diamond-head.jpg',
	},
	{
		id: 'koko-head-challenge',
		title: 'Koko Head Challenge',
		description: 'Take on the famous Koko Head stairs with fellow members of the hiking community. This group hike is intended for hikers looking for a more challenging workout. Participants should bring plenty of water and take breaks as needed.',
		date: new Date('2026-08-29T07:00:00'),
		location: 'Koko Head',
		image: '/koko-head.jpg',
	},
	{
		id: 'beginner-hiking-workshop',
		title: 'Beginner Hiking Workshop',
		description: 'New to hiking? Join us for an introduction to hiking basics. We will discuss trail preparation, what to pack, staying hydrated, trail etiquette, and how to choose a hike that matches your experience level.',
		date: new Date('2026-09-05T10:00:00'),
		location: 'Online',
		image: '/oblogo-better.png',
	},
	{
		id: 'waikiki-social-hike',
		title: 'Waikiki Social Hike',
		description: 'Meet other members of the Outdoor Buddies community during a relaxed group hike near Waikiki. This event is focused on meeting new people, enjoying the outdoors, and building connections with fellow hikers.',
		date: new Date('2026-09-12T08:00:00'),
		location: 'Waikiki',
		image: '/waikiki.jpg',
	},
	{
		id: 'weekend-trail-adventure',
		title: 'Weekend Trail Adventure',
		description: 'Join us for a weekend adventure on one of Oahu’s scenic trails. The group will hike together at a comfortable pace while enjoying the scenery and getting to know other members of the community.',
		date: new Date('2026-09-19T08:30:00'),
		location: 'TBD',
		image: '/oblogo-better.png',
	},
	{
		id: 'hiking-safety-workshop',
		title: 'Hiking Safety Workshop',
		description: 'Learn important safety practices for hiking in Hawaii. Topics will include preparing for changing weather, bringing essential supplies, understanding trail conditions, and what to do if something goes wrong while hiking.',
		date: new Date('2026-09-26T10:00:00'),
		location: 'Online',
		image: '/oblogo-better.png',
	},
	{
		id: 'fall-community-hike',
		title: 'Fall Community Hike',
		description: 'Celebrate the start of fall with a community hike. Hikers of different experience levels are welcome to join us for a morning outdoors and meet other members of the Outdoor Buddies community.',
		date: new Date('2026-10-03T08:00:00'),
		location: 'TBD',
		image: '/oblogo-better.png',
	},
	{
		id: 'oahu-scenic-hike',
		title: 'Oahu Scenic Hike',
		description: 'Explore one of Oahu’s scenic hiking locations with a group of fellow outdoor enthusiasts. This event is a great opportunity to discover a new trail while enjoying Hawaii’s natural scenery.',
		date: new Date('2026-10-10T08:30:00'),
		location: 'TBD',
		image: '/oblogo-better.png',
	},
	{
		id: 'community-trail-maintenance',
		title: 'Community Trail Maintenance',
		description: 'Give back to the local hiking community by helping maintain a popular trail. Volunteers will work together on basic trail cleanup and maintenance while learning more about responsible outdoor recreation.',
		date: new Date('2026-10-17T09:00:00'),
		location: 'TBD',
		image: '/trail-cleanup.jpg',
	},
	{
		id: 'morning-mountain-hike',
		title: 'Morning Mountain Hike',
		description: 'Enjoy a peaceful morning hike through one of Oahu’s mountain trails. We will hike together at a comfortable pace while taking time to enjoy the surrounding scenery and meet other members of the Outdoor Buddies community.',
		date: new Date('2026-10-24T07:30:00'),
		location: 'Tantalus',
		image: '/oblogo-better.png',
	},
	{
		id: 'hiking-photography-walk',
		title: 'Hiking Photography Walk',
		description: 'Bring your camera or phone and join us for a scenic hike focused on photography. Participants will have opportunities to capture landscapes, plants, and other sights along the trail while enjoying a relaxed group hike.',
		date: new Date('2026-10-31T08:00:00'),
		location: 'Manoa Valley',
		image: '/manoa-falls.jpg',
	},
	{
		id: 'outdoor-buddies-community-day',
		title: 'Outdoor Buddies Community Day',
		description: 'Come together with members of the Outdoor Buddies community for a day of hiking, conversation, and outdoor activities. This event is open to members of all experience levels and is a great opportunity to meet new hiking partners.',
		date: new Date('2026-11-07T09:00:00'),
		location: 'TBD',
		image: '/oblogo-better.png',
	},
];

export default defaultEvents;
