import { Difficulty } from '@prisma/client';

export const defaultTrails = [
  {
    name: 'Diamond Head',
    location: '4204 Diamond Head Road',
    difficulty: Difficulty.MODERATE,
    distance: 0.8,
    description: 'One of Oahu’s most famous hikes, Diamond Head offers panoramic views of Waikiki, Honolulu, and the Pacific Ocean from the summit of an ancient volcanic crater. The trail includes steep switchbacks, paved sections, and a series of stairs near the top. Bring water, sunscreen, and comfortable shoes, as there is limited shade along the route. The trail can become crowded, especially during midday.',
    image: '/trails/diamond-head.jpg',
  },
  {
    name: 'Koko Head',
    location: '423 Kaumakani Street',
    difficulty: Difficulty.HARD,
    distance: 0.75,
    description: 'Koko Head is a challenging uphill climb consisting of over 1,000 railroad tie steps leading to a former military lookout. The steep incline provides a demanding workout but rewards hikers with incredible views of Hanauma Bay, the coastline, and eastern Oahu. There is very little shade, so bring plenty of water, wear proper footwear, and avoid hiking during the hottest parts of the day.',
    image: '/trails/koko-head.jpg',
  },
  {
    name: 'Manoa Falls',
    location: '3860 Manoa Road',
    difficulty: Difficulty.EASY,
    distance: 0.8,
    description: 'Manoa Falls is a beginner-friendly rainforest trail that leads through lush vegetation to a 150-foot waterfall. The trail is surrounded by tropical plants and is a great introduction to Oahu hiking. The path can become muddy and slippery after rain, so hiking shoes are recommended. Bring insect repellent, water, and be cautious around wet rocks near the waterfall area.',
    image: '/trails/manoa-falls.jpg',
  },
  {
    name: 'Lanikai Pillbox Trail',
    location: '265 Kaelepulu Drive, Kailua',
    difficulty: Difficulty.MODERATE,
    distance: 0.5,
    description: 'A popular sunrise hike on the east side of Oahu offering stunning views of Lanikai Beach, the Mokulua Islands, and the surrounding coastline. The trail is short but includes steep dirt sections and uneven terrain, especially near the beginning of the climb. The historic pillboxes at the top provide excellent viewpoints and photo opportunities. Bring water, sunscreen, and proper footwear as the trail has little shade and can become slippery after rain.',
    image: '/trails/lanikai-pillbox.png',
  },
  {
    name: 'Makapuʻu Lighthouse Trail',
    location: 'Makapuʻu Point, Waimanalo',
    difficulty: Difficulty.EASY,
    distance: 1.0,
    description: 'A paved coastal trail leading to scenic viewpoints of the Makapuʻu Lighthouse, the Pacific Ocean, and the southeastern coastline of Oahu. During winter months, hikers may spot migrating humpback whales from the lookout areas. The gradual incline makes this trail accessible for most hikers, but there is limited shade along the route. Bring water, sunscreen, and a hat, especially when hiking during the warmer parts of the day.',
    image: '/trails/makapuu-lighthouse.jpg',
  },
  {
    name: 'Kuliouou Ridge Trail',
    location: 'Kuliouou Road, Honolulu',
    difficulty: Difficulty.HARD,
    distance: 2.5,
    description: 'A challenging ridge hike through a variety of Oahu landscapes, including forested areas, exposed ridgelines, and panoramic views of the eastern coastline. The trail includes a long uphill climb with steep sections and uneven terrain, rewarding hikers with views stretching from Koko Head to Waimanalo. Because of the elevation gain and length, hikers should bring plenty of water and allow several hours to complete the trail. Proper hiking shoes are recommended, especially after wet weather.',
    image: '/trails/kuliouou-ridge.png',
  },
  {
    name: 'Aiea Loop Trail',
    location: '99-1849 Aiea Heights Drive, Aiea',
    difficulty: Difficulty.MODERATE,
    distance: 2.7,
    description: 'A scenic forest loop trail located in the central mountains of Oahu, offering views of Halawa Valley, the Koʻolau Mountains, and Pearl Harbor on clear days. The trail passes through native vegetation and shaded forest areas with several viewpoints along the route. Some sections can become muddy and slippery after rain, and hikers should watch for exposed roots and uneven terrain. Bring water, insect repellent, and proper hiking shoes for a comfortable hike.',
    image: '/trails/aiea-loop.jpg',
  },
  {
    name: 'Wiliwilinui Ridge Trail',
    location: 'Waialae Iki Ridge Trail, Honolulu',
    difficulty: Difficulty.HARD,
    distance: 2.5,
    description: 'A challenging ridge hike featuring steep climbs, narrow ridgelines, and some of the best mountain views on Oahu. The trail follows the Koʻolau Mountains and provides views of Honolulu, Maunalua Bay, and the surrounding valleys. Several sections require careful footing, especially along exposed ridges and during wet conditions. Hikers should bring plenty of water, sun protection, and prepare for a demanding uphill climb.',
    image: '/trails/wiliwilinui-ridge.jpg',
  },
  {
    name: 'Kaʻena Point Trail',
    location: 'Farrington Highway, Mokuleia',
    difficulty: Difficulty.MODERATE,
    distance: 2.5,
    description: 'A coastal trail leading to the westernmost point of Oahu, featuring ocean views, native Hawaiian plants, and opportunities to see seabirds and other wildlife. The trail follows an old dirt road along the coastline with little shade and uneven terrain. The protected area at the end of the trail is home to native seabirds and requires visitors to respect posted rules and boundaries. Bring plenty of water, sunscreen, and plan for hot conditions.',
    image: '/trails/kaena-point.jpg',
  },
  {
    name: 'Waimano Falls Trail',
    location: 'Manana Road, Pearl City',
    difficulty: Difficulty.HARD,
    distance: 2.0,
    description: 'A rainforest adventure leading to waterfalls and natural pools in the Waimano Valley area. The trail includes steep downhill sections, muddy terrain, rope-assisted areas, and slippery rocks, especially after rainfall. The waterfall area provides a rewarding destination for hikers looking for a more adventurous experience. Wear sturdy shoes, bring water, and use caution near wet rocks and steep sections.',
    image: '/trails/waimano-falls.jpg',
  },
  {
    name: 'Olomana Three Peaks Trail',
    location: 'Olomana Golf Club Road, Kailua',
    difficulty: Difficulty.HARD,
    distance: 1.5,
    description: 'One of Oahu’s most challenging and technical hikes, featuring steep climbs, exposed ridgelines, and dramatic views of Kailua and the Windward Coast. The trail climbs three separate peaks and includes sections that require scrambling and careful navigation. Due to steep drop-offs and difficult terrain, this hike is recommended only for experienced hikers with proper preparation. Bring water, wear appropriate footwear, and avoid attempting the trail during wet or windy conditions.',
    image: '/trails/olomana-three-peaks.jpg',
  },
];

export default defaultTrails;