export const defaultProfiles = [
  {
    id: 'hy-1',
    name: 'Hanako Yamada',
    image: '/pfps/hy1.jpg',
    summary: 'casual hiker looking for friends',
    description: 'I am excited to go on hikes with all types of people. I just moved here recently, so I am looking to make friends and do less intensive hikes.',
    owner: 'jane@foo.com',
    groupname: 'N/A',
    descimage: null,
  },
  {
    id: 'kb-1',
    name: 'Kim Berley',
    image: '/pfps/kb1.jpg',
    summary: 'more computer science or math nerds welcome',
    description: 'I just like talking about math with people.',
    owner: 'jane@foo.com',
    groupname: 'Mathemagical Hikes',
    descimage: null,
  },
  {
    id: 'rd-1',
    name: 'Renata Daugherty',
    image: '/pfps/rd1.jpg',
    summary: 'Just moved here!',
    description: 'I am excited to be studying marine biology. I love hiking back home and have heard that there are many beautiful ones here.',
    owner: 'jane@foo.com',
    groupname: 'N/A',
    descimage: null,
  },
  {
    id: 'vt-1',
    name: 'Virginia Thompson',
    image: '/pfps/vt1.png',
    summary: 'I am a UH Foreign Exchange Student from France',
    description: 'Excited to meet new people from all around the world. I love all kinds of beaches.',
    owner: 'jane@foo.com',
    groupname: 'N/A',
    descimage: null,
  },
  {
    id: 'pf-1',
    name: 'Payton Frye',
    image: '/pfps/pf1.jpg',
    summary: 'Love cabin life!',
    description: 'I love to go camping and am excited to learn about the best spots! I want to make new friends! It is very nice to meet you all.',
    owner: 'jane@foo.com',
    groupname: 'N/A',
    descimage: null,
  },
  {
    id: 'od-1',
    name: 'Olive Davila',
    image: '/pfps/od1.jpg',
    summary: 'I love icecream!',
    description: 'Just excited to meet new people.',
    owner: 'jane@foo.com',
    groupname: 'N/A',
    descimage: null,
  },
  {
    id: 'lo-1',
    name: 'Lyanna Ochoa',
    image: '/pfps/lo1.jpg',
    summary: 'I love icecream!',
    description: 'Just excited to meet new people.',
    owner: 'jane@foo.com',
    groupname: 'N/A',
    descimage: null,
  },
  {
    id: 'ke-1',
    name: 'Kayla Erickson',
    image: '/pfps/ke1.jpg',
    summary: 'I love learning about new cultures',
    description: 'Just moved here studying more about geography. Currently am taking a class learning about the history of tea which I think is pretty cool. I prefer just having fun and good vibes. Also please any reccomendations for brunch places?',
    owner: 'jane@foo.com',
    groupname: 'N/A',
    descimage: null,
  },
  {
    id: 'hh-1',
    name: 'Holly Haley',
    image: '/pfps/hh1.jpg',
    summary: 'Go Ducks!!!',
    description: 'Have a lot of experience doing hikes? Consider joining our group The Ducks. Seriously though, I have always loved hiking and our family does a big hike every year back in Washington where I am from.',
    owner: 'jane@foo.com',
    groupname: 'Ducks',
    descimage: null,
  },
  {
    id: 'gm-1',
    name: 'Genevieve Morales',
    image: '/pfps/gm1.jpg',
    summary: 'Yes I like Spiderman',
    description: 'Spiderman is great. Everyone likes talking about Spiderman! But yeah I would love to meet new people and if you could stand a rant or two about how great Spiderman is we will get along swimmingly.',
    owner: 'jane@foo.com',
    groupname: 'N/A',
    descimage: null,
  },
  {
    id: 'ah-1',
    name: 'Amy Holloway',
    image: '/pfps/ah1.jpg',
    summary: 'Yes my pfp is a vibe',
    description: 'Love the great outdoors and an even greater brunch afterward with some mimosas.',
    owner: 'jane@foo.com',
    groupname: 'N/A',
    descimage: null,
  },
  {
    id: 'gr-1',
    name: 'Gemma Richards',
    image: '/pfps/gr1.jpg',
    summary: 'Would love to take pictures of the great outdoors with some great buds',
    description: 'Would love to go on more hikes and meet more new poeple.',
    owner: 'jane@foo.com',
    groupname: 'N/A',
    descimage: null,
  },
  {
    id: 'jd-1',
    name: 'John Doe',
    image: '/pfps/jd1.jpg',
    summary: 'looking to add to our group Ducks',
    description: 'I have been hiking for a while on quite intensive hikes. I prefer going with a smaller group, however we are still available to accept a couple more members. Please only consider if you have a decent amount of experience. We go on some pretty intensive hikes.',
    owner: 'john@foo.com',
    groupname: 'Ducks',
    descimage: null,
  },
  {
    id: 'br-1',
    name: 'Bradley Raymond',
    image: '/pfps/br1.jpg',
    summary: 'my favorite food is ramen',
    description: 'I like the ocean and chill vibes',
    owner: 'john@foo.com',
    groupname: 'N/A',
    descimage: null,
  },
  {
    id: 'gh-1',
    name: 'Giovanni Hammond',
    image: '/pfps/gh1.jpg',
    summary: 'Love to take professional photographs of the outdoors',
    description: 'I love taking photos of the outdoors and my friends! Looking to meet new people.',
    owner: 'john@foo.com',
    groupname: 'N/A',
    descimage: null,
  },
  {
    id: 'bc-1',
    name: 'Barrett Case',
    image: '/pfps/bc1.jpg',
    summary: 'Just excited to meet new people',
    description: 'Moved here last year and finally graduated yay! Now that I have more time, I would like to explore more of the outdoors activities here.',
    owner: 'john@foo.com',
    groupname: 'N/A',
    descimage: null,
  },
  {
    id: 'es-1',
    name: 'Elliot Sullivan',
    image: '/pfps/es1.jpg',
    summary: 'Retired man wanting to look at the birds',
    description: 'Just wanted to share with others if interested in learning more about all of the different endemic birds that live here. ',
    owner: 'john@foo.com',
    groupname: 'N/A',
    descimage: null,
  },
  {
    id: 'lk-1',
    name: 'Lucas Kane',
    image: '/pfps/lk1.jpg',
    summary: 'Love checking out new parks',
    description: 'I love looking at the beautiful scenery in parks. Just would like to make some friends, and I like chess!',
    owner: 'john@foo.com',
    groupname: 'N/A',
    descimage: null,
  },
  {
    id: 'ah-1',
    name: 'Adam Hunt',
    image: '/pfps/ah1.jpg',
    summary: 'Like running and chill vibes',
    description: 'I like running back home in Arizona, and I just moved here and would like to meet some new people. Lemme know if you are interested in the best ever butternut squash soup recipe btw.',
    owner: 'john@foo.com',
    groupname: 'N/A',
    descimage: null,
  },
  {
    id: 'sb-1',
    name: 'Sergio Bishop',
    image: '/pfps/sb1.jpg',
    summary: 'Getting back into guitar and tuning into nature (pun intended)',
    description: 'I am just a beginner but if anyone would like to get together in a band sometime that would be nice. I just want to try and connect more iwth nature; nature always finds a way to inspire.',
    owner: 'john@foo.com',
    groupname: 'N/A',
    descimage: null,
  },
  {
    id: 'ad-1',
    name: 'Alden Dunn',
    image: '/pfps/ad1.jpg',
    summary: 'Favorite Food is watermelon on a hot summer day',
    description: 'I have quite a bit of experience doing hikes here. Mostly just here for our group the Ducks. Please consider applying if you have a lot of experience. Love the more intensive hikes with a great crew!',
    owner: 'john@foo.com',
    groupname: 'Ducks',
    descimage: null,
  },
  {
    id: 'ab-1',
    name: 'Anthony Ballard',
    image: '/pfps/ab1.jpg',
    summary: 'Love taking pictures of wildlife',
    description: 'Just moved here and am studying marine biology at UH. I am very excited to take lots of pictures of all of the cool animals here. Did you know that like 90 percent of animals here are endemic? something like that. Also the weather here is super nice.',
    owner: 'john@foo.com',
    groupname: 'N/A',
    descimage: null,
  },
  {
    id: 'tr-1',
    name: 'Tony Rowe',
    image: '/pfps/tr1.jpg',
    summary: 'Need coffee yesterday',
    description: 'Need to meet new people that are not from work.',
    owner: 'john@foo.com',
    groupname: 'N/A',
    descimage: null,
  },
  {
    id: 'lc-1',
    name: 'Lennon Carpenter',
    image: '/pfps/lc1.jpg',
    summary: 'My favorite food is pizza bagels',
    description: 'I am a foreign exchange student from Britain. Just heard about this through a friend and would like to meet more people.',
    owner: 'john@foo.com',
    groupname: 'N/A',
    descimage: null,
  },
  {
    id: 'ts-1',
    name: 'The Steins',
    image: '/pfps/ts1.jpg',
    summary: 'We love meeting new people',
    description: 'We are Jill and Jack Stein. We love going on hikes together but we would love to meet new people! Just moved here a little while ago.',
    owner: 'john@foo.com',
    groupname: 'N/A',
    descimage: null,
  },
];

export default defaultProfiles;